version: "1.0"
info:
  model: int-scaffold
packages:
- name: FR_STT_OrderManagementProject
  gitServerName: staillanibm
  gitUrl: https://github.com/staillanibm
  gitUsername: staillanibm
  gitBranch: main
services:
- serviceName: project.fr_stt_ordermanagement.integrations:processOrderBatch
  packages:
  - name: FR_STT_OrderManagementProject
    version: "1.0"
