version: "1.0"
info:
  model: int-scaffold
packages:
- name: FR_STT_OrderManagementProject
  gitServerName: staillanibm
  gitUrl: https://github.com/staillanibm
  gitUsername: staillanibm
  gitBranch: main
- name: WmJDBCAdapter
  version: 10.3.0.0.34
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:order_db
  packages:
  - name: FR_STT_OrderManagementProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:insertOrder
  packages:
  - name: FR_STT_OrderManagementProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:nextValOrderId
  packages:
  - name: FR_STT_OrderManagementProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.fr_stt_ordermanagement.integrations:processOrderBatch
  packages:
  - name: FR_STT_OrderManagementProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: pub.list:sizeOfList
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: project.fr_stt_ordermanagement.integrations:testNextVal
  packages:
  - name: FR_STT_OrderManagementProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
configurationVariables:
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionSettings.dbType
  : MSSQL
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionSettings.serverName
  : contabo.sttlab.eu
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionSettings.password
  : "{AES}zxtjDVPnPMSWIVvNbTQB+H9awpHAyfXYCxLWEZQhnoE="
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionSettings.keyStore
  : ""
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionSettings.networkProtocol
  : ""
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionSettings.databaseName
  : sandbox
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionSettings.trustStore
  : ""
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionSettings.portNumber
  : "1433"
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionManagerSettings.poolable
  : "true"
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionSettings.transactionType
  : LOCAL_TRANSACTION
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionEnabled
  : "false"
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionSettings.user
  : sa
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.FR_STT_OrderManagementProject.project.fr_stt_ordermanagement.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.order_db.connectionManagerSettings.startupRetryCount
  : "0"
